# -*- coding: utf-8 -*-
"""chatterbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PjGvcvOmQ0EWENLzqoZdAPBCO8NjbaXv
"""

!pip install chatterbot
!pip install spacy

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

from spacy.cli import download
download('en_core_web_sm')

class ENGSM:
  ISO_639_1 = 'en_core_web_sm'

chatbot = ChatBot('botAmumu', tagger_language = ENGSM)

conversa = [
            "coe",
            "eai, tranquilo?",
            "tranquilo",
            "qual a boa de hoje ?",
            "aprender coisa de bot"
]

trainer = ListTrainer(chatbot)
trainer.train(conversa)

while True:
  mensagem = input("mande uma mensagem para o bot: ")
  if mensagem == 'parar':
    break
  
  resposta = chatbot.get_response(mensagem)
  print(resposta)

#chatbot.storage.drop() #limpar banco de dados do bot